In [24]:

import numpy as np

In [28]:
arr1 =np.arange(1,7)
arr2 = np.arange(11, 17)
arr3 = np.arange(21,27)
arr4 = np.arange(31,37)
arr = np.hstack([arr1, arr2, arr3, arr4])
arr = arr.reshape(4,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])

In [29]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])

In [31]:
arr[[1],:,:][:,0,2][0]
# arr[[1],:,:][0,0,2] 같음
# arr[1,0,2]

13

In [45]:
arr[1,:,:][:,[1]]

array([[12],
       [15]])

In [34]:
arr[1,:,1]

array([12, 15])

In [44]:
arr[1,0:2,1:2]

array([[12],
       [15]])

In [46]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [48]:
arr[[True,False,True,True,False]]

array([1, 3, 4])

In [50]:
arr[[True,False,True,True,False,False,False]] 
# Element-wise 연산가 안되서  자리가 맞지 않으면 오류남.

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 7

In [51]:
arr[[0,2,3]] #자리 위치를 지정해서 가져오기

array([1, 3, 4])

In [52]:
arr[arr>4]

array([5])

In [53]:
arr [np.arange(1,6)>4] 
# 4보다 큰것

array([5])

In [57]:
arr[np.arange(6,1,-1) <3] 

array([5])

In [58]:
np.random.seed(100)
arr = np.random.randint(1,100,1000)

In [63]:
##3의 배수이거나 5의 배수인것의 합
arr[(arr % 3 == 0) | (arr % 5 == 0)].sum()


25046

In [72]:
idx = np.arange(1000)[(arr % 3 == 0) | (arr % 5 == 0)]
idx
arr[idx].sum()

25046

In [68]:
##3의 배수이거나 5의 배수인것의 합의 갯수
sum(arr[(arr % 3 == 0) | (arr % 5 == 0)] % 2 ==1)


252

In [64]:
s = 0
for i in arr:
    if i % 5 == 0 or i % 3 ==0:
        s+= i
s

25046

In [76]:
arr = np.array([2,3,4,7])

In [77]:
#boolean True 
boolean_ = [False,True,False,True]

In [82]:
arr[boolean_]
np.arange(4)[boolean_]

array([1, 3])

In [80]:
arr[[1,3]]

array([3, 7])

In [85]:
arr = np.arange(1,21).reshape(4, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [86]:
arr[0,1:-1]

array([2, 3, 4])

In [90]:
arr[0,1:arr.shape[1]-1]

array([2, 3, 4])

In [93]:
arr[:arr.shape[0],:int(arr.size/arr.shape[0])]
#int를 넣지 않으면 소숫점때문에 불가능

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [94]:
repr(arr[[0],1:-1])

'array([[2, 3, 4]])'

In [95]:
arr[:,-2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [96]:
arr[:,[4,3,2,1,0]]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

In [132]:
arr[1:3,[-2,-3,-4]]

array([[ 9,  8,  7],
       [14, 13, 12]])

In [133]:
arr[1:3,::-1][:,1:4]

array([[ 9,  8,  7],
       [14, 13, 12]])

In [135]:
arr[1:3,-2:-5:-1]

array([[ 9,  8,  7],
       [14, 13, 12]])

In [136]:
np.arange(5,1,-1)
arr[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [139]:
#나열하는 것 뒤집기
arr[-2:-4:-1,-2:-5:-1]

array([[14, 13, 12],
       [ 9,  8,  7]])

In [142]:
#양수로
arr[2:0:-1,3:0:-1]

array([[14, 13, 12],
       [ 9,  8,  7]])

In [145]:
x = np.random.choice(np.arange(10,1000),1)
y = np.arange(x[0])

In [144]:
y

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [146]:
y.size

590

In [160]:
y.reshape(10,59)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175

In [226]:
#사이즈 확인하는 방법(추천하지는 않음)
s = 0
xx= []
for i in range(y.size + 1):
    for j in range(y.size + 1):
        try:
            y.reshape(i,j)
            s += 1
            xx.append((i,j))
        except:
            pass

In [227]:
s

1

In [228]:
xx

[(0, 0)]

In [229]:
#사이즈 확인하는 방법(추천하지는 않음)
import numpy as np

# 예시 넘파이 배열 생성
y = np.array([])

# 배열의 차원 확인
print("차원:", y.ndim)

# 배열의 모양(크기) 확인
print("모양:", y.shape)

# 배열의 전체 요소 개수 확인
print("요소 개수:", y.size)

차원: 1
모양: (0,)
요소 개수: 0


In [242]:
x =[1,2,3]
y ={(1,2),(1,3),(2,3),}

In [243]:
product(list(np.ayb.size))

NameError: name 'product' is not defined

In [244]:
sum([y.size == i*j for i,j in list(product(np.arange(1,y.size+1),np.arange(1,y.size+1)[:3]))])

NameError: name 'product' is not defined

In [245]:
result = np.where(condition,True,False)
print(result)

NameError: name 'condition' is not defined

In [246]:
x = np.random.randint(20,100,200)

In [247]:
np.where(x % 3 ==0,3,0)

array([3, 0, 3, 3, 0, 0, 3, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       0, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 0, 3, 3, 3, 0, 0, 0, 3, 3, 0,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 3, 0, 3, 0, 0, 3,
       3, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 0, 3, 0, 0, 3, 0, 3, 0, 3, 3, 3,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 3, 0, 0, 3,
       0, 0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 0, 3, 3, 0, 0, 0, 0, 3, 3, 3, 0,
       0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0,
       3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 0, 3, 3, 0, 3, 0, 3,
       0, 0])

In [248]:
##3의 배수 3, 5의 배수 5 ,0
np.where(x % 3 ==0,3,
         np.where(x%5==0,5,0))

array([3, 0, 3, 3, 0, 0, 3, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 3,
       0, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 0, 3, 3, 3, 0, 0, 0, 3, 3, 5,
       0, 0, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 3, 0, 3, 0, 0, 3,
       3, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 0, 3, 0, 0, 3, 0, 3, 5, 3, 3, 3,
       0, 3, 5, 0, 0, 0, 0, 0, 0, 0, 5, 3, 0, 0, 3, 3, 3, 3, 0, 0, 3, 5,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 5, 3, 0, 5, 3,
       0, 0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 5, 3, 3, 0, 0, 0, 0, 3, 3, 3, 0,
       5, 5, 0, 0, 0, 3, 0, 0, 5, 0, 0, 3, 0, 5, 3, 0, 0, 0, 5, 5, 5, 0,
       3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 0, 3, 3, 0, 3, 0, 3,
       0, 5])

In [249]:
a = np.array(np.meshgrid(np.arange(1, y.size+1), np.arange(1, y.size+1))).T.reshape(-1, 2)

AttributeError: 'set' object has no attribute 'size'

In [250]:
a[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [251]:
np.where(y.size/a[:,0]*a[:,1],True,False).sum()

AttributeError: 'set' object has no attribute 'size'

In [252]:
x.reshape(-1,7)

ValueError: cannot reshape array of size 200 into shape (7)

In [253]:
x.reshape(-1,6)

ValueError: cannot reshape array of size 200 into shape (6)

In [304]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [305]:
arr.shape

(2, 4)

In [307]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [302]:
def xxx(data,x,y):
    sh1 = data.shape[0]
    sh2 = data.shape[1]
    new_data = []
    for i in range(sh1):
        for j in range(sh2):
            new_data.append(data[i,j])
    for i in range(x):
        print(new_data[i*y:i*y+2])
           
    
    return new_data


In [303]:
xxx(arr,3,2)

[1, 2]
[3, 4]
[5, 6]


[1, 2, 3, 4, 5, 6]

In [287]:
xxx(arr,3,2)

[1, 2]
[1, 2]
[1, 2]


[1, 2, 3, 4, 5, 6]

In [282]:
xxx(arr,1,1)

[1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]

In [278]:
arr.shape

(2, 3)

In [279]:
np.array(arr).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [280]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [308]:
arr.flatten() #평탄화/사용을 더 많이 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [310]:
arr.ravel() #flatten랑 결과값이 같음

array([1, 2, 3, 4, 5, 6, 7, 8])

In [312]:
arr = np.random.randn(3,4)

In [313]:
arr.shape

(3, 4)