In [10]:
import numpy as np

In [100]:
cond1 = True
cond2 = True
cond3 = False
condition = [cond1,cond2,cond3]
len (condition) == sum(condition)
sum(condition) > 0

True

In [95]:
np.all([True,True,False])

False

In [96]:
np.any([True,True,False])

True

In [92]:
False in[True,False,False]

True

In [378]:
class MyNumpy:
    def __init__(self,x,y,method):
        self.x = x
        self.y = y
        if method == "dot":
            self.dot()
        if self.y.ndim > self.x.ndim:
            self.x, self.y = self.y, self.x
        self.rows = range(self.x.shape[0])
        self.cols = range(self.x.shape[1])
        cond1 = isinstance(self.y,(int,float))
        if cond1:
            self.y = np.array(self.y)
        if self.y.ndim == 0:
            self.broadcast()
        if self.y.ndim == 1 and self.y.shape[0] > 1:
            if self.x.shape[1] == self.y.shape[0]:
                self.element_wise_broadcast_vector()
        if self.x.shape == self.y.shape:
            self.element_wise()
        if self.y.ndim == 2 and (1 in self.y.shape):
            if self.x.shape[0] == self.y.shape[0]:
                self.element_wise_col()
            elif self.x.shape[1] == self.y.shape[1]:
                self.element_wise_row()
            elif 1 in self.x.shape:
                if self.x.shape[0] == self.y.shape[1] or self.x.shape[1] == self.y.shape[0]:
                    if self.x.shape[1] == 1:
                        self.x, self.y = self.y, self.x
                    self.value = np.zeros((self.y.shape[0],self.x.shape[1]))
                    self.rows = range(self.y.shape[0])
                    self.cols = range(self.x.shape[1])
                    self.element_wise_broadcast_matrix()         
                else:
                    'fail'
                
                
            
    def broadcast(self):
        self.value = np.zeros_like(self.x)
        rows = range(self.x.shape[0])
        cols = range(self.x.shape[1])
        for row in rows:
            for col in cols:
                self.value[row,col] = self.x[row,col] + self.y
        return self.value
    
    def element_wise_broadcast_vector(self):
        self.value = np.zeros_like(self.x)
        rows = range(self.x.shape[0])
        cols = range(self.x.shape[1])
        for row in rows:
            for col in cols:
                self.value[row,col] = self.x[row,col] + self.y[col]
        return self.value

    def element_wise(self):
        self.value = np.zeros_like(self.x)
        rows = range(self.x.shape[0])
        cols = range(self.y.shape[1])
        for row in rows:
            for col in cols:
                self.value[row,col] = self.x[row,col] + self.y[row,col]
        return self.value

    def element_wise_col(self):
        self.value = np.zeros_like(self.x)
        for col in self.cols:
            for row in self.rows:
                self.value[row,col] = self.x[row,col] + self.y[row,0]
        return self.value
        
    def element_wise_row(self):
        self.value = np.zeros_like(self.x)
        for row in self.rows:
            for col in self.cols:
                self.value[row,col] = self.x[row,col] + self.y[0,col]
        return self.value
    def element_wise_broadcast_matrix(self):
        for row in self.rows:
            for col in self.cols:
                self.value[row,col] = self.x[0,col] + self.y[row,0]
        return self.value
    def dot(self):
        if self.x.shape[1] == self.y.shape[0]:
            self.value = np.zeros((self.x.shape[0],self.y.shape[1]))
            for row in range(self.x.shape[0]):
                for col in range(self.y.shape[1]):
                    
                    # s = 0
                
                    # for idx in range(self.x.shape[1]):
                    #     s += self.x [row,idx]*self.y[idx,col]
                    self.value[row,col] = self.element_wise_(self.x[row,:],self.y[:,col])
                        
                    # s = 0
                    # for row1 in range(self.x.shape[0]):
                    #     for col1 in range(self.y.shape[1]):
                    #         s += self.x[row,col1] * self.y[row1,col]                   
                    #     self.value[row,col] = s
                  
            
        else:
            print('dot 불가능')

    def element_wise_(self,x,y):
        s = 0
        for i in range(len(x)): 
            s += x[i]*y[i]
        return s

In [379]:
x1 = np.random.randint(1,10,size=(3,2))
x = x1[0,:]
y = x1[1,:]
def element_wise(x,y):
    s = 0
    for i in range(len(x)):
        s += x[i]*y[i]
    return s

element_wise(x,y)


39

In [377]:
x = np.random.seed(1)
x = np.random.randint(1,10,size=(3,2))
y = np.random.randint(1,10,size=(2,2))
a = MyNumpy(x,y, 'dot')


NameError: name 'element_wise_self' is not defined

In [358]:
a.value

array([[75., 87.],
       [51., 47.],
       [14., 17.]])

In [359]:
a.y

array([[8, 7],
       [3, 5]])

In [360]:
a.x + a.y

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [224]:
y =  np.random.randn(3,1)
x = np.random.randn(3,4)
if (y.ndim == 2) and (1 in y.shape)

SyntaxError: expected ':' (1703306271.py, line 3)

In [228]:
a.value

AttributeError: 'MyNumpy' object has no attribute 'value'

In [201]:
a.broadcast()

ValueError: setting an array element with a sequence.

In [187]:
a.value

array([[16, 19, 16],
       [11, 11, 12],
       [18, 17, 13],
       [15, 16, 13],
       [15, 13, 15]])

In [181]:
np.random.randn(3,4).shape
np.zeros_like(x)

array([0., 0., 0.])

In [178]:
a.broadcast()

In [206]:
a.x+a.y

array([[14, 17,  8],
       [ 9,  2,  9],
       [16, 14,  5],
       [ 6,  8, 12],
       [14,  7, 14]])

In [146]:
rows = range(a.x.shape[0])
cols = range(a.x.shape[1])
for row in rows:
    for col in cols:
             print(f'a[{row},{col}]=={a.x[row,col]} + {a.y}')

a[0,0]==6 + 10
a[0,1]==9 + 10
a[0,2]==6 + 10
a[1,0]==1 + 10
a[1,1]==1 + 10
a[1,2]==2 + 10
a[2,0]==8 + 10
a[2,1]==7 + 10
a[2,2]==3 + 10
a[3,0]==5 + 10
a[3,1]==6 + 10
a[3,2]==3 + 10
a[4,0]==5 + 10
a[4,1]==3 + 10
a[4,2]==5 + 10


In [105]:
x+np.array(range(6))


ValueError: operands could not be broadcast together with shapes (5,3) (6,) 

In [75]:
a.result

'fail'

In [176]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [177]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
def solution(matrix_A, matrix_B):
    answer = []
    for i in range(len(matrix_A)):
        row = []
        for j in range(len(matrix_A[i])):
            row.append(matrix_A[i][j])
        answer.append(row)            
    return answer