In [1]:
li = [1,2,3,'abc',len,{'a':10}]

In [3]:
li[5]

{'a': 10}

In [5]:
id(li[1])

140717980042056

In [6]:
a = li[1]

In [7]:
#numpy np 클래스
import numpy as np

In [8]:
# nd 어래이
type(np)

module

In [10]:
# 스칼라
type(1)

int

In [12]:
# 스칼라
a = repr(type(1))

In [13]:
np.array(1) + 2

3

In [14]:
# 양의 값 넌파이 array으로 바뀜
print(type(np.array(1)))

<class 'numpy.ndarray'>


In [15]:
a= np.array(1) 

In [16]:
a

array(1)

In [17]:
b=1
dir(b)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [18]:
a.shape

()


# 평균
$$\sum \limits_{X=i}^{n}\frac{X}{n} $$

$$\frac{1}{n}\cdot\sum\limits_{i=1}^{n} x_{i}$$

In [43]:
x= np.array ([1,2,3,4])

In [28]:
(1/X.size)*np.sum(X)

2.5

In [31]:
X.size**-1*np.sum(X)

2.5

5 

In [34]:
5+ np.array([1,5])

array([ 6, 10])

In [36]:
# 엘레멘트가 똑같은 값끼리 계산
np.array([1,4]) + np.array([4,1])

array([5, 5])

# 개수가 동일해야 계산이 가능함

In [38]:
# 원소의 개수,변수의 개수
np.array([1,4]) .shape

(2,)

In [39]:
np.array([4,1]) .shape

(2,)

In [45]:
np.sum((X-np.sum(X) * (1/X.size))**2)/(X.size-1)

1.6666666666666667

In [46]:
np.var(X)

1.25

In [47]:
np.array([1,2,3]).dtype

dtype('int32')

In [51]:
np.array([1,2,3.],dtype = 'int').dtype

dtype('int32')

In [54]:
np.array([1,2,3.],dtype = 'bool').dtype

dtype('bool')

In [55]:
np.array('shahjdkhf')

array('shahjdkhf', dtype='<U9')

In [56]:
len('shahjdkhf')

9

In [57]:
np.array([1,2,3.],dtype = 'O')

array([1, 2, 3.0], dtype=object)

In [60]:
x = np.array([1,2,3])

In [61]:
x + 2

array([3, 4, 5])

In [2]:
import numpy as np
#board cast
x= np.array([1,2,3]).reshape(1,3)
x + np.array([1])

array([[2, 3, 4]])

In [6]:
import numpy as np
##board cast
x= np.array([1,2,3]).reshape(1,3)
(x + np.array(1).spape #스칼라
(x + np.array([1]).spape #벡터
(x + np.array([[1]]).spape ##1*1 array


SyntaxError: incomplete input (1646103171.py, line 6)

In [15]:
import numpy as np
##board cast
x= np.array([1,2,3])
(x + np.array([1,2,3])).shape #vector
##매트릭스 element wise
x = np.array([1,2,3]).reshape(3,1)
x + np.array([1,2,3]) #벡터 elementwise and boardcast
(x+np.array(([[1],[2],[3]]))).shape

(3, 1)

In [68]:
a= np.array([[90,100,70],
      [100,100,100],
      [90,100,100]])

In [69]:
a.shape

(3, 3)

In [4]:
import matplotlib.pyplot as plt

In [5]:
img = plt.imread('cat1.jpg')

In [ ]:
plt.imshow(img)

In [ ]:
plt.img[100:,50:600,:]

In [ ]:
## matrix element wise(n,m)
x= np.array(range(1,7)).reshape(3,2)
try:
    (x + np.array([1,2,3])).shape
except Exception as e:
    print(e)
try:
    x + np.array([1,2,3]).reshape
except Exception as e:
    print(e)
(x + np.array[1,2,3].reshape(3,1)).shape   

In [11]:
import numpy as np

In [12]:
## element wise board cast
x = np.array([1,2,3]).reshape(3,1)
x+np.array([1,2,3]) ##vector
y = np.array([1,2,3]).reshape(1,3)
y+np.array([1,2,3]) ##vector
## 교환법칙 성립
(np.array([1,2,3]) + x).shape
(np.array([1,2,3]) + y).shape
##element wise board cast case
x+y
y+x

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [23]:
##비교 연산,논리 연산
(x + y) > 10
(((x + y) < 10) & ((x-y)< 5)) & np.array([True,False,True]).reshape(1,3)
arr1 = np.array([True]*9).reshape(3,3) 
arr1 & np.array([True,False,False]).reshape(3,1)


array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [31]:
## 내적 연산, matrix 곱
x = np.array(range(1,7)).reshape(3,2)
y= np.array ([[1],[2]])
print(np.dot(x,y))
x@y
np.dot(y,x)

[[ 5]
 [11]
 [17]]


ValueError: shapes (2,1) and (3,2) not aligned: 1 (dim 1) != 3 (dim 0)

In [45]:
import numpy as np
class Array:
    def __init__(self,*args):
        self._x = [arg for arg in args if isinstance (arg,(int,float))]
    def reshape(self,*args):
        shape = tuple ([arg for arg in args])
        self._x = np.array(self._x).reshape(shape)

In [46]:
arr = Array(1,2,3,4)

In [47]:
arr.reshape(2,2)

In [48]:
arr._x

array([[1, 2],
       [3, 4]])

In [19]:
import numpy as np

class Array:
    def __init__(self, x, y, method):
        self.x = x  
        self.y = y  
      
    def broad_cast(self):
        if self.x.ndim == 1:
            self.x = list(self.x)
            result = []
            for val in self.x:
                result.append(val + self.y)
            result = np.array(result)  
        elif self.x.ndim == 2:
            shape = self.x.shape
            result = []
            for rows in self.x:  
                for cols in list(rows):
                    result.append(cols + self.y)
            result = np.array(result).reshape(shape) 
        
        return result

In [20]:
x = np.array([1,2,3,4,5])
y= 2
arr = Array(x,y)

TypeError: Array.__init__() missing 1 required positional argument: 'method'

In [21]:
arr.x
result = []
if arr.x.ndim == 2:
    arr.x = list(arr.x)
    for col in arr.x:
        for col in list (row):
            result.append(col+arr.y)
    result = np.array(result).reshape(shape)

NameError: name 'arr' is not defined

In [22]:
result

NameError: name 'result' is not defined

In [25]:
np.array([1,2,3,4,5,6]).reshape(2,3).shape [0]

2

In [26]:
list(np.array([1,2,3,4]).reshape(2,2)

SyntaxError: incomplete input (3108795217.py, line 1)

In [47]:
## 1. thell the one_child
## 2. my choice
## 3. my_answer = [one_child, my_choice] 
## 4. original_child my_answer
import random
import numpy as np

def child_answer(x):
    s=0
    for _ in range(x) : 
        one_child = random.choice(['f','m']) 
        if one_child == 'f':
            my_choice = 'm'
            original_child = random.choice([[0,0],[1,0],[0,1]])
        else :
            my_choice = 'f'
            original_child = random.choice([[1,1],[1,0],[0,1]])
        if one_child == 'f' :
            one_child = 0
        else :
            one_child = 1
        if my_choice == 'f' :
            my_choice = 0
        else :
            my_choice = 1
        my_answer = [one_child, my_choice]
        s+=((sum(my_answer) == sum(original_child)))
    return s/x

In [1]:
import numpy as np
score = np.random.choice(range(60,101),(10,3))

In [4]:
score[np.argmax (np.sum(score,1)),0]

98

In [61]:
score[:,0]

array([79, 73, 99, 72, 86, 70, 92, 96, 79, 95])

In [59]:
score[:,0]+score[:,0]+score[:,0]

array([79, 93, 89])

In [64]:
total = score[:,0]+score[:,1]+score[:,2]
max(total)

292

In [51]:
## 1. thell the one_child
## 2. my choice
## 3. my_answer = [one_child, my_choice] 
## 4. original_child my_answer
import random
import numpy as np

def child_answer(x):
    s=0
    for _ in range(x) : 
        one_child = random.choice(['f','m']) 
        if one_child == 'f':
            my_choice = random.choice(['f','m'])
            original_child = random.choice([[0,0],[1,0],[0,1]])
        else :
            my_choice = 'm'
            original_child = random.choice([[1,1],[1,0],[0,1]])
        if one_child == 'f' :
            one_child = 0
        else :
            one_child = 1
        if my_choice == 'f' :
            my_choice = 0
        else :
            my_choice = 1
        my_answer = [one_child, my_choice]
        s+=((sum(my_answer) == sum(original_child)))
    return s/x

In [52]:
child_answer(10000)

0.409

In [46]:
one_child

'm'

In [5]:
import sys
sys.path #SYS는 Path이라는 속성이 있음

['C:\\Users\\user\\python',
 'C:\\Users\\user\\anaconda3\\python311.zip',
 'C:\\Users\\user\\anaconda3\\DLLs',
 'C:\\Users\\user\\anaconda3\\Lib',
 'C:\\Users\\user\\anaconda3',
 '',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32\\lib',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\Pythonwin',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\win32',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\win32\\lib',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\Pythonwin']

In [6]:
sys.path.append('C:\\test')

In [7]:
sys.path

['C:\\Users\\user\\python',
 'C:\\Users\\user\\anaconda3\\python311.zip',
 'C:\\Users\\user\\anaconda3\\DLLs',
 'C:\\Users\\user\\anaconda3\\Lib',
 'C:\\Users\\user\\anaconda3',
 '',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32\\lib',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\Pythonwin',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\win32',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\win32\\lib',
 'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\Pythonwin',
 'C:\\test']

In [8]:
import test

ModuleNotFoundError: No module named 'test1'